import AdminPannelCard from "@/components/shared/AdminPannelCard";
import { adminPannelCardInfo } from "@/data/data";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "سبزلرن | SabzLearn",
  description: "Generated by create next app",
  icons: {
    icon: "/logo/fav.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="max-w-4xl p-6 mx-auto">
      <h2 className="font-bold  text-3xl">amirrajj عزیز؛ خوش اومدی 🙌</h2>
      <div className="grid sm:grid-cols-3 md:grid-cols-4 gap-4 mt-14">
        {adminPannelCardInfo.map(item=>(
            <AdminPannelCard key={item.id} bgColor={item.bgColor} count={item.count} icon={item.icon} linkUrl={`/admin-pannel/${item.link}`} title={item.title}  />
        ))}
      </div>
      {children}
    </div>
  );
}
