import AdminPannelMap from "@/components/admin/AdminPannelMap";
import { getUser } from "@/helpers/getCurrentUser";
import { IUser } from "@/interfaces/types";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "سبزلرن | SabzLearn",
  description: "Generated by create next app",
  icons: {
    icon: "/logo/fav.png",
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user : IUser = await getUser()
  return (
    <div className="max-w-4xl p-6 mx-auto">
      <h2 className="font-bold  text-3xl">{user?.username} عزیز؛ خوش اومدی 🙌</h2>
      <AdminPannelMap/>
      {children}
    </div>
  );
}
